name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Log into ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
    
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Terraform Init & Apply
        working-directory: Terraform  # Use the correct case here
        run: |
          terraform init
          terraform apply -auto-approve -var="image_tag=latest"

      - name: Build and Push upload image
        working-directory: services/service-upload
        run: |
          docker build -t upload:latest .
          docker tag upload:latest ${{ steps.login-ecr.outputs.registry }}/sandhyak-upload:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/sandhyak-upload:latest

      - name: Build and Push queue image
        working-directory: services/service-queue
        run: |
          docker build -t queue:latest .
          docker tag queue:latest ${{ steps.login-ecr.outputs.registry }}/sandhyak-queue:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/sandhyak-queue:latest

  snyk:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Snyk
        run: |
          curl -Lo snyk https://static.snyk.io/cli/latest/snyk-linux
          chmod +x snyk
          sudo mv snyk /usr/local/bin/

      - name: Snyk test sandhyak-upload
        working-directory: services/sandhyak-upload
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test

      - name: Snyk test sandhyak-queue
        working-directory: services/sandhyak-queue
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test
